// ============================================================================
// SkillRegistry - Register, discover, and manage agent skills
// Reference: WorkBuddy skill system with metadata tracking
// ============================================================================

import { readFile, writeFile, mkdir, readdir, stat, rm } from 'node:fs/promises';
import { join, resolve, dirname } from 'node:path';

// --- Types ---

export interface SkillMetadata {
  /** Unique skill identifier */
  name: string;
  /** Human-readable description */
  description: string;
  /** Author */
  author?: string;
  /** Version (semver) */
  version: string;
  /** Tags for categorization and search */
  tags: string[];
  /** Supported model providers (empty = all) */
  providers?: string[];
  /** Required tools for this skill */
  requiredTools?: string[];
  /** Whether this skill was auto-generated */
  autoGenerated?: boolean;
  /** Creation date */
  createdAt: string;
  /** Last update date */
  updatedAt: string;
  /** File size in bytes */
  sizeBytes?: number;
  /** Reviewed at date */
  reviewedAt?: string;
}

export interface SkillDefinition {
  /** Skill metadata */
  metadata: SkillMetadata;
  /** SKILL.md content (the skill prompt/instructions) */
  content: string;
  /** Associated script files */
  scripts?: Record<string, string>;
  /** Associated reference files */
  references?: string[];
}

export interface SkillSearchParams {
  /** Search query string */
  query?: string;
  /** Filter by tags */
  tags?: string[];
  /** Filter by provider compatibility */
  provider?: string;
  /** Include auto-generated skills */
  includeAutoGenerated?: boolean;
  /** Maximum results */
  limit?: number;
}

// --- SkillRegistry ---

export class SkillRegistry {
  private skillsDir: string;
  private cache = new Map<string, SkillDefinition>();
  private initialized = false;

  constructor(skillsDir?: string) {
    this.skillsDir = skillsDir || join(process.env.HOME || process.env.USERPROFILE || '~', '.nova-cli', 'skills');
  }

  /**
   * Initialize the registry by loading all skills from disk.
   */
  async initialize(): Promise<void> {
    try {
      await mkdir(this.skillsDir, { recursive: true });
    } catch {
      // Directory may already exist
    }

    const entries = await readdir(this.skillsDir, { withFileTypes: true });
    for (const entry of entries) {
      if (entry.isDirectory()) {
        const skillPath = join(this.skillsDir, entry.name);
        try {
          const skill = await this.loadSkill(entry.name);
          if (skill) {
            this.cache.set(entry.name, skill);
          }
        } catch {
          // Skip invalid skills
        }
      }
    }

    this.initialized = true;
  }

  /**
   * Register a new skill.
   */
  async register(skill: SkillDefinition): Promise<void> {
    const skillDir = join(this.skillsDir, skill.metadata.name);
    await mkdir(skillDir, { recursive: true });

    // Write SKILL.md
    const skillMdPath = join(skillDir, 'SKILL.md');
    const fullContent = this.buildSkillMd(skill.metadata, skill.content);
    await writeFile(skillMdPath, fullContent, 'utf-8');

    // Write script files
    if (skill.scripts) {
      const scriptsDir = join(skillDir, 'scripts');
      await mkdir(scriptsDir, { recursive: true });
      for (const [filename, content] of Object.entries(skill.scripts)) {
        await writeFile(join(scriptsDir, filename), content, 'utf-8');
      }
    }

    // Update cache
    skill.metadata.updatedAt = new Date().toISOString();
    this.cache.set(skill.metadata.name, skill);
  }

  /**
   * Get a skill by name.
   */
  async get(name: string): Promise<SkillDefinition | null> {
    if (!this.initialized) {
      await this.initialize();
    }

    if (this.cache.has(name)) {
      return this.cache.get(name)!;
    }

    return this.loadSkill(name);
  }

  /**
   * Search for skills matching the given criteria.
   */
  async search(params: SkillSearchParams): Promise<SkillDefinition[]> {
    if (!this.initialized) {
      await this.initialize();
    }

    let results = Array.from(this.cache.values());

    // Filter by auto-generated
    if (!params.includeAutoGenerated) {
      results = results.filter((s) => !s.metadata.autoGenerated);
    }

    // Filter by provider
    if (params.provider) {
      results = results.filter(
        (s) =>
          !s.metadata.providers ||
          s.metadata.providers.length === 0 ||
          s.metadata.providers.includes(params.provider!)
      );
    }

    // Filter by tags
    if (params.tags && params.tags.length > 0) {
      results = results.filter((s) =>
        params.tags!.some((tag) => s.metadata.tags.includes(tag))
      );
    }

    // Filter by query
    if (params.query) {
      const query = params.query.toLowerCase();
      results = results.filter(
        (s) =>
          s.metadata.name.toLowerCase().includes(query) ||
          s.metadata.description.toLowerCase().includes(query) ||
          s.metadata.tags.some((t) => t.toLowerCase().includes(query))
      );
    }

    // Sort by relevance (name match first, then description match)
    if (params.query) {
      const query = params.query.toLowerCase();
      results.sort((a, b) => {
        const aNameMatch = a.metadata.name.toLowerCase().includes(query) ? 2 : 0;
        const bNameMatch = b.metadata.name.toLowerCase().includes(query) ? 2 : 0;
        const aDescMatch = a.metadata.description.toLowerCase().includes(query) ? 1 : 0;
        const bDescMatch = b.metadata.description.toLowerCase().includes(query) ? 1 : 0;
        return (bNameMatch + bDescMatch) - (aNameMatch + aDescMatch);
      });
    }

    // Limit results
    if (params.limit) {
      results = results.slice(0, params.limit);
    }

    return results;
  }

  /**
   * List all registered skills.
   */
  async list(): Promise<SkillDefinition[]> {
    if (!this.initialized) {
      await this.initialize();
    }
    return Array.from(this.cache.values());
  }

  /**
   * Remove a skill.
   */
  async remove(name: string): Promise<boolean> {
    const skillDir = join(this.skillsDir, name);

    try {
      await rm(skillDir, { recursive: true, force: true });
    } catch {
      return false;
    }

    this.cache.delete(name);
    return true;
  }

  /**
   * Get the skills directory path.
   */
  getSkillsDir(): string {
    return this.skillsDir;
  }

  /**
   * Build the full SKILL.md content with metadata header.
   */
  private buildSkillMd(metadata: SkillMetadata, content: string): string {
    const header = `---
name: ${metadata.name}
description: ${metadata.description}
version: ${metadata.version}
author: ${metadata.author || 'unknown'}
tags: ${metadata.tags.join(', ')}
${metadata.providers ? `providers: ${metadata.providers.join(', ')}` : ''}
${metadata.requiredTools ? `requiredTools: ${metadata.requiredTools.join(', ')}` : ''}
${metadata.autoGenerated ? 'autoGenerated: true' : ''}
createdAt: ${metadata.createdAt}
updatedAt: ${metadata.updatedAt}
---

`;
    return header + content;
  }

  /**
   * Load a skill from disk.
   */
  private async loadSkill(name: string): Promise<SkillDefinition | null> {
    const skillDir = join(this.skillsDir, name);
    const skillMdPath = join(skillDir, 'SKILL.md');

    try {
      const rawContent = await readFile(skillMdPath, 'utf-8');
      const { metadata, content } = this.parseSkillMd(rawContent);

      // Load scripts
      const scripts: Record<string, string> = {};
      const scriptsDir = join(skillDir, 'scripts');
      try {
        const entries = await readdir(scriptsDir);
        for (const entry of entries) {
          if (entry.endsWith('.ts') || entry.endsWith('.js') || entry.endsWith('.sh') || entry.endsWith('.py')) {
            scripts[entry] = await readFile(join(scriptsDir, entry), 'utf-8');
          }
        }
      } catch {
        // No scripts directory
      }

      const fileStat = await stat(skillMdPath);

      return {
        metadata: { ...metadata, sizeBytes: fileStat.size },
        content,
        scripts: Object.keys(scripts).length > 0 ? scripts : undefined,
      };
    } catch {
      return null;
    }
  }

  /**
   * Parse SKILL.md content into metadata and body.
   */
  private parseSkillMd(rawContent: string): {
    metadata: SkillMetadata;
    content: string;
  } {
    const frontmatterMatch = rawContent.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
    if (!frontmatterMatch) {
      return {
        metadata: {
          name: 'unknown',
          description: 'No description',
          version: '0.0.0',
          tags: [],
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
        },
        content: rawContent,
      };
    }

    const frontmatter = frontmatterMatch[1];
    const content = frontmatterMatch[2];

    const parseField = (field: string): string => {
      const match = frontmatter.match(new RegExp(`${field}:\\s*(.+)`));
      return match ? match[1].trim() : '';
    };

    const parseArray = (field: string): string[] => {
      const raw = parseField(field);
      if (!raw) return [];
      return raw.split(',').map((s) => s.trim()).filter(Boolean);
    };

    const parseBool = (field: string): boolean => {
      const raw = parseField(field);
      return raw.toLowerCase() === 'true';
    };

    const name = parseField('name') || 'unknown';
    return {
      metadata: {
        name,
        description: parseField('description'),
        version: parseField('version') || '0.0.0',
        author: parseField('author') || undefined,
        tags: parseArray('tags'),
        providers: parseArray('providers').length > 0 ? parseArray('providers') : undefined,
        requiredTools: parseArray('requiredTools').length > 0 ? parseArray('requiredTools') : undefined,
        autoGenerated: parseBool('autoGenerated'),
        createdAt: parseField('createdAt') || new Date().toISOString(),
        updatedAt: parseField('updatedAt') || new Date().toISOString(),
      },
      content,
    };
  }

  /**
   * Recursively remove a directory.
   */
  private async removeDirectory(dirPath: string): Promise<void> {
    await rm(dirPath, { recursive: true, force: true });
  }
}
